version: '3'
services:
  app:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: brmedapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234